imports:
   - { resource: services.yaml }


services:
  # Example Bind Service interface
  # This will be enabled only in APP_ENV=prod (.env)
  App\Service\Upload\Contract\FileUploaderInterface: '@App\Service\Upload\S3FileUploader'